[package]
name = "multi-sender-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "Skyzox",]

[dev-dependencies]

[dependencies.multi-sender]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.34.1"
